### PR TITLE
Fix dav1d.rs

### PR DESCRIPTION
**Pull request by Luni-4**
When I try to open dav1d.rs, all the code is on a single line. This PR fixes this problem.

Thank you in advance for your review!

### CODE REVIEW

**Comment by Luni-4** [comment]
Is there any problem with this one? I can fix it :)

**Comment by lu-zero** [comment]
I think I sent a comment about it before, but apparently it got lost =/

I disabled rustfmt to not force the users to use it, not sure if the default now it is use if available.

If it is the patch can land.

**Comment by Luni-4** [comment]
> I think I sent a comment about it before, but apparently it got lost =/
> 
> I disabled rustfmt to not force the users to use it, not sure if the default now it is use if available.
> 
> If it is the patch can land.

I see. 
Hmm, is there any reason why a user shouldn't use `rustfmt`? I'm not an expert, but without it, one should split the entire david.rs on more lines manually. Does the problem happen to you too or it is just me?

**Comment by lu-zero** [comment]
It seems that it would fail hard, but I guess our easier life trumps the theoretical user without rustfmt for now.

If the need arises we could add a check for rustfmt and act accordingly on our side.

**Comment by Luni-4** [comment]
Perfect! I agree. Thanks for the merge

**Pull request merged**
