### PR TITLE
wip: Try to unbreak the windows CI

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by lu-zero** [comment]
https://github.com/rust-av/dav1d-rs/actions/runs/4415174943/jobs/7737806758#step:5:14 Looks like the pkg-config provide assumes a default search path that does not exists with the gcc in use.

**Comment by sdroege** [comment]
The pkg-config file probably assumes the msys-mingw default search path, but the mingw Rust toolchain doesn't know about such things.

**Comment by lu-zero** [comment]
If you have windows to check which is the correct path we can just pass it locally.

**Comment by sdroege** [comment]
Not currently but I'll have to work on a Windows-related project next week or the week after. Will take a look then :)

**Comment by sdroege** [comment]
Mh but I don't have msys. Would you be OK with switching the Windows CI from mingw/msys to MSVC?

**Comment by sdroege** [comment]
Obsoleted by https://github.com/rust-av/dav1d-rs/pull/77

**Pull request closed without merging**
