### PR TITLE
Add an Error type

### PR DESCRIPTION
**Pull request by linkmauve**
This is useful for keeping it as a source for other error types, `i32` is otherwise pretty inexpressive.

Also fixes this crate for platforms where `EAGAIN` is already negative.

### CODE REVIEW

**Comment by philn** [comment]
LGTM

**Review by lu-zero — APPROVED** [review]
Sure, why not.

**Comment by lu-zero** [comment]
Do you have other fixes and changes pending? I'd make a release with your changes soon.

**Comment by linkmauve** [comment]
Nothing pending, it seems to work well in https://github.com/image-rs/image/pull/1398

**Comment by lu-zero** [comment]
Perfect :)

**Pull request merged**
